//------------------------------------------------------------------------------
/*
    this file is part of beast: https://github.com/vinniefalco/beast
    copyright 2013, vinnie falco <vinnie.falco@gmail.com>

    permission to use, copy, modify, and/or distribute this software for any
    purpose  with  or without fee is hereby granted, provided that the above
    copyright notice and this permission notice appear in all copies.

    the  software is provided "as is" and the author disclaims all warranties
    with  regard  to  this  software  including  all  implied  warranties  of
    merchantability  and  fitness. in no event shall the author be liable for
    any  special ,  direct, indirect, or consequential damages or any damages
    whatsoever  resulting  from  loss  of use, data or profits, whether in an
    action  of  contract, negligence or other tortious action, arising out of
    or in connection with the use or performance of this software.

    portions based on soci - the c++ database access library: 

    soci: http://soci.sourceforge.net/

    this file incorporates work covered by the following copyright
    and permission notice:

    copyright (c) 2004 maciej sobczak, stephen hutton, mateusz loskot,
    pawel aleksander fedorynski, david courtney, rafal bobrowski,
    julian taylor, henning basold, ilia barahovski, denis arnaud,
    daniel lidstr鰉, matthieu kermagoret, artyom beilis, cory bennett,
    chris weed, michael davidsaver, jakub stachowski, alex ott, rainer bauer,
    martin muenstermann, philip pemberton, eli green, frederic chateau,
    artyom tonkikh, roger orr, robert massaioli, sergey nikulov,
    shridhar daithankar, s鰎en meyer-eppler, mario valesco.

    boost software license - version 1.0, august 17th, 2003

    permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "software") to use, reproduce, display, distribute,
    execute, and transmit the software, and to prepare derivative works of the
    software, and to permit third-parties to whom the software is furnished to
    do so, all subject to the following:

    the copyright notices in the software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the software, in whole or in part, and
    all derivative works of the software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    the software is provided "as is", without warranty of any kind, express or
    implied, including but not limited to the warranties of merchantability,
    fitness for a particular purpose, title and non-infringement. in no event
    shall the copyright holders or anyone distributing the software be liable
    for any damages or other liability, whether in contract, tort or otherwise,
    arising from, out of or in connection with the software or the use or other
    dealings in the software.
*/
//==============================================================================

#ifndef beast_sqdb_session_h_included
#define beast_sqdb_session_h_included

#include <beast/smart_ptr/sharedptr.h>
#include <beast/module/core/memory/sharedsingleton.h>

namespace beast {
namespace sqdb {

/*============================================================================*/
/**
  @brief a session for the embedded database.

  @ingroup vf_db
*/
class session
{
public:
    session();
    ~session();

    // deprecated!
    // opens the deferred clone
    explicit session(session const& deferredclone);
    error clone();

    /**
      open a database.

      the database at the specified path is opened. the connection string is
      a set of "{key}={value}" pairs separated with the pipe symbol ('|').
      choices for key and value are:

      @code

      timeout = (number) || "infinite"

      mode    = "read" || "write" || "create"

      cache   = "shared" || "private"

      threads = "single" || "multi"

      @endcode
    */
    error open(string filename,
               std::string options = "timeout=infinite|mode=create|threads=multi");

    void close();

    void begin();
    error commit();
    void rollback();

    bool in_transaction()
    {
        return m_bintransaction;
    }

    detail::once_type once(error& error);
    detail::prepare_type prepare;

    rowid last_insert_rowid();

    std::ostringstream& get_query_stream();

    void log_query(std::string const& query);

    void set_got_data(bool bgotdata);
    bool got_data() const;

    sqlite3* get_connection()
    {
        return m_connection;
    }

private:
    error hard_exec(std::string const& query);

private:
    class sqlite3;
    sharedptr <sharedsingleton <sqlite3> > m_instance;
    bool m_bintransaction;
    sqlite3* m_connection;
    string m_filename;
    std::string m_connectstring;

    std::ostringstream m_query_stream;
    bool m_bgotdata;
};

} // sqdb
} // beast

#endif
