//------------------------------------------------------------------------------
/*
    this file is part of beast: https://github.com/vinniefalco/beast
    copyright 2013, vinnie falco <vinnie.falco@gmail.com>

    permission to use, copy, modify, and/or distribute this software for any
    purpose  with  or without fee is hereby granted, provided that the above
    copyright notice and this permission notice appear in all copies.

    the  software is provided "as is" and the author disclaims all warranties
    with  regard  to  this  software  including  all  implied  warranties  of
    merchantability  and  fitness. in no event shall the author be liable for
    any  special ,  direct, indirect, or consequential damages or any damages
    whatsoever  resulting  from  loss  of use, data or profits, whether in an
    action  of  contract, negligence or other tortious action, arising out of
    or in connection with the use or performance of this software.

    portions based on soci - the c++ database access library: 

    soci: http://soci.sourceforge.net/

    this file incorporates work covered by the following copyright
    and permission notice:

    copyright (c) 2004 maciej sobczak, stephen hutton, mateusz loskot,
    pawel aleksander fedorynski, david courtney, rafal bobrowski,
    julian taylor, henning basold, ilia barahovski, denis arnaud,
    daniel lidstr鰉, matthieu kermagoret, artyom beilis, cory bennett,
    chris weed, michael davidsaver, jakub stachowski, alex ott, rainer bauer,
    martin muenstermann, philip pemberton, eli green, frederic chateau,
    artyom tonkikh, roger orr, robert massaioli, sergey nikulov,
    shridhar daithankar, s鰎en meyer-eppler, mario valesco.

    boost software license - version 1.0, august 17th, 2003

    permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "software") to use, reproduce, display, distribute,
    execute, and transmit the software, and to prepare derivative works of the
    software, and to permit third-parties to whom the software is furnished to
    do so, all subject to the following:

    the copyright notices in the software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the software, in whole or in part, and
    all derivative works of the software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    the software is provided "as is", without warranty of any kind, express or
    implied, including but not limited to the warranties of merchantability,
    fitness for a particular purpose, title and non-infringement. in no event
    shall the copyright holders or anyone distributing the software be liable
    for any damages or other liability, whether in contract, tort or otherwise,
    arising from, out of or in connection with the software or the use or other
    dealings in the software.
*/
//==============================================================================

namespace beast {
namespace sqdb {
namespace detail {

// vfalco what the heck is this?!
#ifdef c
#undef c
#endif

const error sqliteerror(const char* sourcefilename,
                        int linenumber,
                        int sqliteerrorcode)
{
    /*
    bassert (sqliteerrorcode != sqlite_row &&
             sqliteerrorcode != sqlite_done);
    */

    error e;
    string s;
    error::code c;

    switch (sqliteerrorcode)
    {
        // should never get these two here but include them just in case
    case sqlite_row:
    case sqlite_done:

    case sqlite_ok:
        // this is fine, and lets us avoid having to explicitly
        // check for sqlite_ok and just deal in terms of the error object.
        c = error::success;
        break;

    case sqlite_error:
        s = "an sqlite error or missing database was encountered";
        c = error::general;
        break;

    case sqlite_internal:
        s = "sqlite encountered an internal logic error";
        c = error::unexpected;
        break;

    case sqlite_perm:
        s = "sqlite was denied file access permission";
        c = error::filenoperm;
        break;

    case sqlite_abort:
        s = "the sqlite operation was canceled due to a callback";
        c = error::canceled;
        break;

    case sqlite_busy:
        s = "the sqlite database file is locked";
        c = error::fileinuse;
        break;

    case sqlite_locked:
        s = "the sqlite database table was locked";
        c = error::fileinuse;
        break;

    case sqlite_nomem:
        s = "sqlite ran out of memory";
        c = error::nomemory;
        break;

    case sqlite_readonly:
        s = "sqlite tried to write to a read-only database";
        c = error::filenoperm;
        break;

    case sqlite_interrupt:
        s = "the sqlite operation was interrupted";
        c = error::canceled;
        break;

    case sqlite_ioerr:
        s = "sqlite encountered a device i/o error";
        c = error::fileioerror;
        break;

    case sqlite_corrupt:
        s = "the sqlite database is corrupt";
        c = error::invaliddata;
        break;

    case sqlite_full:
        s = "the sqlite database is full";
        c = error::filenospace;
        break;

    case sqlite_cantopen:
        s = "the sqlite database could not be opened";
        c = error::filenotfound;
        break;

    case sqlite_protocol:
        s = "sqlite encountered a lock protocol error";
        c = error::badparameter;
        break;

    case sqlite_empty:
        s = "the sqlite database is empty";
        c = error::nomoredata;
        break;

    case sqlite_schema:
        s = "the sqlite database scheme was changed";
        c = error::invaliddata;
        break;

    case sqlite_toobig:
        s = "the sqlite string or blob was too large";
        c = error::filenospace;
        break;

    case sqlite_constraint:
        s = "the sqlite operation was aborted due to a constraint violation";
        c = error::badparameter;
        break;

    case sqlite_mismatch:
        s = "the sqlite data was mismatched";
        c = error::badparameter;
        break;

    case sqlite_misuse:
        s = "the sqlite library parameter was invalid";
        c = error::badparameter;
        break;

    case sqlite_nolfs:
        s = "the sqlite platform feature is unavailable";
        c = error::badparameter;
        break;

    case sqlite_auth:
        s = "sqlite authorization was denied";
        c = error::filenoperm;
        break;

    case sqlite_format:
        s = "the auxiliary sqlite database has an invalid format";
        c = error::invaliddata;
        break;

    case sqlite_range:
        s = "the sqlite parameter was invalid";
        c = error::badparameter;
        break;

    case sqlite_notadb:
        s = "the file is not a sqlite database";
        c = error::invaliddata;
        break;

    default:
        s << "an unknown sqlite3 error code #"
          << string(sqliteerrorcode)
          << "was returned";
        c = error::general;
        break;
    }

    if (c != error::success)
        e.fail(sourcefilename, linenumber, s, c);

    return e;
}

} // detail
} // sqdb
} // beast
