## message_buffer unit tests
##

import('env')
import('env_cpp11')
import('boostlibs')
import('platform_libs')
import('polyfill_libs')

env = env.clone ()
env_cpp11 = env_cpp11.clone ()

boost_libs = boostlibs(['unit_test_framework','system'],env) + [platform_libs]

objs = env.object('message_boost.o', ["message.cpp"], libs = boost_libs)
objs += env.object('alloc_boost.o', ["alloc.cpp"], libs = boost_libs)
prgs = env.program('test_message_boost', ["message_boost.o"], libs = boost_libs)
prgs += env.program('test_alloc_boost', ["alloc_boost.o"], libs = boost_libs)

if env_cpp11.has_key('wspp_cpp11_enabled'):
   boost_libs_cpp11 = boostlibs(['unit_test_framework'],env_cpp11) + [platform_libs] + [polyfill_libs]
   objs += env_cpp11.object('message_stl.o', ["message.cpp"], libs = boost_libs_cpp11)
   objs += env_cpp11.object('alloc_stl.o', ["alloc.cpp"], libs = boost_libs_cpp11)
   prgs += env_cpp11.program('test_message_stl', ["message_stl.o"], libs = boost_libs_cpp11)
   prgs += env_cpp11.program('test_alloc_stl', ["alloc_stl.o"], libs = boost_libs_cpp11)

return('prgs')
