## autobahn test client example
##

import('env')
import('env_cpp11')
import('boostlibs')
import('platform_libs')
import('polyfill_libs')

env = env.clone ()
env_cpp11 = env_cpp11.clone ()

prgs = []

# if a c++11 environment is available build using that, otherwise use boost
if env_cpp11.has_key('wspp_cpp11_enabled'):
   all_libs = boostlibs(['system'],env_cpp11) + [platform_libs] + [polyfill_libs]
   prgs += env_cpp11.program('testee_client', ["testee_client.cpp"], libs = all_libs)
else:
   all_libs = boostlibs(['system','random'],env) + [platform_libs] + [polyfill_libs]
   prgs += env.program('testee_client', ["testee_client.cpp"], libs = all_libs)

return('prgs')
