#!/bin/sh
#
# record the version of the source that we are compiling.
# we keep a record of the git revision in util/version.cc. this source file
# is then built as a regular source file as part of the compilation process.
# one can run "strings executable_filename | grep _build_" to find the version of
# the source that we used to build the executable file.

outfile="$pwd/util/build_version.cc"

git_sha=""
if command -v git >/dev/null 2>&1; then
    git_sha=$(git rev-parse head 2>/dev/null)
fi

cat > "${outfile}" <<eof
#include "build_version.h"
const char* rocksdb_build_git_sha = "rocksdb_build_git_sha:${git_sha}";
const char* rocksdb_build_git_datetime = "rocksdb_build_git_datetime:$(date)";
const char* rocksdb_build_compile_date = __date__;
const char* rocksdb_build_compile_time = __time__;
eof
