## wsperf
##

import('env')
import('boostlibs')
import('wslib')
import('platform_libs')

localenv = env.clone ()

sources = ["wsperf.cpp",
           "request.cpp",
           "case.cpp",
           "generic.cpp",
           "stress_handler.cpp",
           "stress_aggregate.cpp",
           "wscmd.cpp"]

libs = [wslib] + boostlibs(['system',
                            'date_time',
                            'regex',
                            'thread',
                            'random',
                            'chrono',
                            'program_options']) + [platform_libs]

prg = localenv.program('wsperf', sources, libs = libs)

return('prg')
