## logger unit tests
##

import('env')
import('env_cpp11')
import('boostlibs')
import('platform_libs')
import('polyfill_libs')

env = env.clone ()
env_cpp11 = env_cpp11.clone ()

boost_libs = boostlibs(['unit_test_framework','system'],env) + [platform_libs]

objs = env.object('logger_basic_boost.o', ["basic.cpp"], libs = boost_libs)
prgs = env.program('logger_basic_boost', ["logger_basic_boost.o"], libs = boost_libs)

if env_cpp11.has_key('wspp_cpp11_enabled'):
   boost_libs_cpp11 = boostlibs(['unit_test_framework','system'],env_cpp11) + [platform_libs] + [polyfill_libs]
   objs += env_cpp11.object('logger_basic_stl.o', ["basic.cpp"], libs = boost_libs_cpp11)
   prgs += env_cpp11.program('logger_basic_stl', ["logger_basic_stl.o"], libs = boost_libs_cpp11)

return('prgs')
