## endpoint unit tests
##

import('env')
import('env_cpp11')
import('boostlibs')
import('platform_libs')
import('polyfill_libs')
import('tls_libs')

env = env.clone ()
env_cpp11 = env_cpp11.clone ()

boost_libs = boostlibs(['unit_test_framework','system'],env) + [platform_libs] + [tls_libs]

objs = env.object('endpoint_boost.o', ["endpoint.cpp"], libs = boost_libs)
prgs = env.program('test_endpoint_boost', ["endpoint_boost.o"], libs = boost_libs)

if env_cpp11.has_key('wspp_cpp11_enabled'):
   boost_libs_cpp11 = boostlibs(['unit_test_framework','system'],env_cpp11) + [platform_libs] + [polyfill_libs] + [tls_libs]
   objs += env_cpp11.object('endpoint_stl.o', ["endpoint.cpp"], libs = boost_libs_cpp11)
   prgs += env_cpp11.program('test_endpoint_stl', ["endpoint_stl.o"], libs = boost_libs_cpp11)

return('prgs')
