## telemetry_server
##

import('env')
import('boostlibs')
import('wslib')
import('platform_libs')

localenv = env.clone ()

sources = ["telemetry_server.cpp"]

libs = [wslib, platform_libs] + boostlibs(['system',
                                           'date_time',
                                           'regex',
                                           'thread'])

prg = localenv.program('telemetry_server', sources, libs = libs)

return('prg')
