## iostream transport unit tests
##

import('env')
import('env_cpp11')
import('boostlibs')
import('platform_libs')
import('polyfill_libs')

env = env.clone ()
env_cpp11 = env_cpp11.clone ()

boost_libs = boostlibs(['unit_test_framework','system'],env) + [platform_libs]

objs = env.object('iostream_base_boost.o', ["base.cpp"], libs = boost_libs)
objs += env.object('iostream_connection_boost.o', ["connection.cpp"], libs = boost_libs)
objs += env.object('iostream_endpoint_boost.o', ["endpoint.cpp"], libs = boost_libs)
prgs = env.program('test_iostream_base_boost', ["iostream_base_boost.o"], libs = boost_libs)
prgs += env.program('test_iostream_connection_boost', ["iostream_connection_boost.o"], libs = boost_libs)
prgs += env.program('test_iostream_endpoint_boost', ["iostream_endpoint_boost.o"], libs = boost_libs)

if env_cpp11.has_key('wspp_cpp11_enabled'):
   boost_libs_cpp11 = boostlibs(['unit_test_framework'],env_cpp11) + [platform_libs] + [polyfill_libs]
   objs += env_cpp11.object('iostream_base_stl.o', ["base.cpp"], libs = boost_libs_cpp11)
   objs += env_cpp11.object('iostream_connection_stl.o', ["connection.cpp"], libs = boost_libs_cpp11)
   objs += env_cpp11.object('iostream_endpoint_stl.o', ["endpoint.cpp"], libs = boost_libs_cpp11)
   prgs += env_cpp11.program('test_iostream_base_stl', ["iostream_base_stl.o"], libs = boost_libs_cpp11)
   prgs += env_cpp11.program('test_iostream_connection_stl', ["iostream_connection_stl.o"], libs = boost_libs_cpp11)
   prgs += env_cpp11.program('test_iostream_endpoint_stl', ["iostream_endpoint_stl.o"], libs = boost_libs_cpp11)

return('prgs')
