## http unit tests
##

import('env')
import('env_cpp11')
import('boostlibs')
import('platform_libs')
import('polyfill_libs')

env = env.clone ()
env_cpp11 = env_cpp11.clone ()

boost_libs = boostlibs(['unit_test_framework'],env) + [platform_libs]

objs = env.object('parser_boost.o', ["parser.cpp"], libs = boost_libs)
prgs = env.program('test_http_boost', ["parser_boost.o"], libs = boost_libs)

if env_cpp11.has_key('wspp_cpp11_enabled'):
   boost_libs_cpp11 = boostlibs(['unit_test_framework'],env_cpp11) + [platform_libs] + [polyfill_libs]
   objs += env_cpp11.object('parser_stl.o', ["parser.cpp"], libs = boost_libs_cpp11)
   prgs += env_cpp11.program('test_http_stl', ["parser_stl.o"], libs = boost_libs_cpp11)

return('prgs')
