## random number generation unit tests
##

import('env')
import('env_cpp11')
import('boostlibs')
import('platform_libs')
import('polyfill_libs')

env = env.clone ()
env_cpp11 = env_cpp11.clone ()

boost_libs = boostlibs(['unit_test_framework','random','system'],env) + [platform_libs]

objs = env.object('random_none_boost.o', ["none.cpp"], libs = boost_libs)
objs += env.object('random_device_boost.o', ["random_device.cpp"], libs = boost_libs)
prgs = env.program('test_random_none_boost', ["random_none_boost.o"], libs = boost_libs)
prgs += env.program('test_random_device_boost', ["random_device_boost.o"], libs = boost_libs)

if env_cpp11.has_key('wspp_cpp11_enabled'):
   boost_libs_cpp11 = boostlibs(['unit_test_framework'],env_cpp11) + [platform_libs] + [polyfill_libs]
   objs += env_cpp11.object('random_none_stl.o', ["none.cpp"], libs = boost_libs_cpp11)
   objs += env_cpp11.object('random_device_stl.o', ["random_device.cpp"], libs = boost_libs_cpp11)
   prgs += env_cpp11.program('test_random_none_stl', ["random_none_stl.o"], libs = boost_libs_cpp11)
   prgs += env_cpp11.program('test_random_device_stl', ["random_device_stl.o"], libs = boost_libs_cpp11)

return('prgs')
