language: c
compiler: gcc
script: make test-travis
before_install:
  - sudo apt-get update  -qq
  - sudo apt-get install -qq gcc-multilib
  - sudo apt-get install -qq valgrind

env:
  - lz4_travis_ci_env=travis-install
  - lz4_travis_ci_env=streaming-examples
  - lz4_travis_ci_env=cmake
  - lz4_travis_ci_env=dist
  - lz4_travis_ci_env=test-lz4
  - lz4_travis_ci_env=test-lz4c
  - lz4_travis_ci_env=test-lz4c32
  - lz4_travis_ci_env=test-fullbench
  - lz4_travis_ci_env=test-fullbench32
  - lz4_travis_ci_env=test-fuzzer
  - lz4_travis_ci_env=test-fuzzer32
  - lz4_travis_ci_env=test-frametest
  - lz4_travis_ci_env=test-frametest32
  - lz4_travis_ci_env=test-mem

matrix:
  fast_finish: true
